name: MParT CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-doc:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Run CMake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -DKokkos_ENABLE_PTHREAD=ON -DKokkos_ENABLE_SERIAL=ON ../

      - name: Build
        run: cd build; make

      - name: Run Tests
        run: cd build; ./RunTests --kokkos-cores=2

      - name: Build Docs
        run: cd build; make doc


