name: docs

on:
  push:
    branches:
      - 147-render-notebooks-into-sphinx-documentation

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install doxygen and sphinx
        run: |
          cd ${{ github.workspace }}
          chmod +x .github/install-doxygen.sh
          .github/install-doxygen.sh 1.9.2

      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: quay.io/hbonart/mpart:latest
          path: /home/jovyan/examples/python/.
      
      - name: Move notebooks into documentation
        run: cp ${{ steps.extract.outputs.destination }}/* ${{ github.workspace }}/docs/source/tutorials/.
        
      - name: Install sphinx extensions
        run: |
          pip3 install -IU pygments==2.7
          pip3 install -U sphinx breathe pydata-sphinx-theme jinja2 sphinx_panels nbsphinx pandoc nbconvert

      - name: Run CMake
        run: |
          cd ${{ github.workspace }}
          mkdir build && cd build
          cmake -DKokkos_ENABLE_PTHREAD=ON -DKokkos_ENABLE_SERIAL=ON ../

      - name: Build Docs
        run: cd build; make sphinx

      #- name: Push to gh-pages
      #  uses: peaceiris/actions-gh-pages@v3.6.1
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: build/docs/sphinx/

