name: external-lib-tests

on:
  push:
    branches:
      - dannys4/issue50
  pull_request: {}

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: mpart

      - name: Checkout Kokkos
        uses: actions/checkout@v3
        with:
          repository: kokkos/kokkos
          path: kokkos

      # - name: Checkout Catch2
      #   uses: actions/checkout@v3
      #   with:
      #     repository: catchorg/Catch2
      #     path: catch2

      # - name: Checkout Eigen
      #   uses: actions/checkout@v3
      #   with:
      #     repository: live-clones/eigen
      #     path: eigen

      # - name: Checkout Pybind11
      #   uses: actions/checkout@v3
      #   with:
      #     repository: pybind/pybind11.git
      #     path: pybind11
      #     ref: master

      - name: Install Kokkos
        run: |
          cd $GITHUB_WORKSPACE/kokkos
          mkdir build && cd build
          cmake -DKokkos_ENABLE_PTHREAD=ON \
                -DKokkos_ENABLE_SERIAL=ON  \
                -DKokkos_CXX_STANDARD=17   \
                ../
          sudo make install

      - name: Install Eigen
        run: $CONDA/bin/conda install -c conda-forge eigen

      - name: Install Catch2
        run: $CONDA/bin/conda install -c conda-forge catch2

      - name: Install Pybind11
        run: $CONDA/bin/conda install -c conda-forge pybind11

      - name: Configure MParT
        run: |
          cd $GITHUB_WORKSPACE/mpart
          mkdir build && cd build
          cmake ../

      - name: Build MParT
        run: cd $GITHUB_WORKSPACE/mpart/build; make

      - name: Run Tests
        run: cd $GITHUB_WORKSPACE/mpart/build; ./RunTests --kokkos-cores=2 --reporter junit -o test-results.xml

      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: build/test-results.xml