name: docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install doxygen and sphinx
        run: sudo apt-get install -y doxygen
        
      - name: Install sphinx extensions 
        run: pip3 install sphinx breathe pydata-sphinx-theme

      - name: Run CMake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake -DKokkos_ENABLE_PTHREAD=ON -DKokkos_ENABLE_SERIAL=ON ../

      - name: Build Docs
        run: cd build; make sphinx

      - name: Push to gh-pages 
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/sphinx/

